#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged
npm test
echo "Checking for spelling errors"
files=$(git diff --cached --name-only)
npx cspell --no-summary --config ./.modules/shared/.cspell.json $files || echo "Review the list of possible misspelled words above and correct anything that needs changing."
