#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

. "./.modules/shared/update.lib.sh"

log "Running lint-staged"
npx lint-staged
log "Running npm test"
npm test
log "Checking for spelling errors"
FILES=$(git diff --cached --name-only)
if [ "$FILES" ]; then
  SPELLING_ERRORS=$(npx cspell --no-summary --no-progress --show-context --show-suggestions --no-must-find-files --config ./.modules/shared/.cspell.json $FILES)
  if [ "$SPELLING_ERRORS" ]; then
    echo $SPELLING_ERRORS
    warn "Review the list of possible misspelled words above and correct anything that needs changing."
  else
    success "No spelling errors were found - good job!"
  fi
else
  info "No files staged for spell checking"
fi
success "Successfully passed all validation checks"
